select 
	BIKE_ID, BIKE_LATITUDE, BIKE_LONGITUDE, FENCE_LATITUDE, FENCE_LONGITUDE, FENCE_LATITUDE_0, FENCE_LONGITUDE_0, FENCE_LATITUDE_1, FENCE_LONGITUDE_1, 
	FENCE_LATITUDE_2, FENCE_LONGITUDE_2, FENCE_LATITUDE_3, FENCE_LONGITUDE_3, DISTANCE, IS_INSIDE, FENCE_ID, ROAD, TIME
--into
--	final_in_data
from 
	gathered_in_bike_data as t1
left join fence_position as t2 on
	t1.FENCE_LATITUDE_0 = t2.LATITUDE_0 and t1.FENCE_LONGITUDE_0 = t2.LONGITUDE_0 and t1.FENCE_LATITUDE_1 = t2.LATITUDE_1 and t1.FENCE_LONGITUDE_1 = t2.LONGITUDE_1


select 
	BIKE_ID, BIKE_LATITUDE, BIKE_LONGITUDE, FENCE_LATITUDE, FENCE_LONGITUDE, FENCE_LATITUDE_0, FENCE_LONGITUDE_0, FENCE_LATITUDE_1, FENCE_LONGITUDE_1, 
	FENCE_LATITUDE_2, FENCE_LONGITUDE_2, FENCE_LATITUDE_3, FENCE_LONGITUDE_3, DISTANCE, IS_INSIDE, FENCE_ID, ROAD, TIME
--into
--	final_out_data
from 
	gathered_out_bike_data as t1
left join fence_position as t2 on
	t1.FENCE_LATITUDE_0 = t2.LATITUDE_0 and t1.FENCE_LONGITUDE_0 = t2.LONGITUDE_0 and t1.FENCE_LATITUDE_1 = t2.LATITUDE_1 and t1.FENCE_LONGITUDE_1 = t2.LONGITUDE_1